
name: Process Bikeshed to HTML

on:
  push:

jobs:

  changes:
  
    runs-on: ubuntu-20.04
  
    outputs:
      changes: ${{ steps.changes.outputs.any_modified }}
    
    steps:

      - name: Checkout latest change
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.push.ref }}
    
      - id: branches
        name: Get branch names.
        uses: tj-actions/branch-names@v8
    
      - id: affected
        name: Discover last checked commit
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ steps.branches.outputs.current_branch }}
          error-on-no-successful-workflow: "true"
          last-successful-event: "push"
          workflow-id: "bikeshed.yml"
    
      - id: changes
        name: Check for changed files
        uses: tj-actions/changed-files@v42
        with:
          base_sha: ${{ steps.affected.outputs.base }}
          files: |
            spec/identity/index.bs

  main:

    runs-on: ubuntu-20.04

    permissions:
      contents: write
  
    needs: changes
    
    if: ${{ needs.changes.outputs.changes == 'true' }}

    steps:

      - name: Checkout latest change
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.push.ref }}
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Bikeshed
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade bikeshed
          bikeshed update

      - name: Run Bikeshed
        run: |
          bikeshed spec spec/identity/index.bs

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: process Bikeshed to HTML (CI)'
