
name: Process Bikeshed to HTML

on:
  push:

jobs:

  changes:
  
    runs-on: ubuntu-20.04
  
    outputs:
      changes: ${{ steps.changes.outputs.any_modified }}
    
    steps:

      - name: Checkout latest change
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.push.ref }}
    
      - id: branches
        name: Get branch names.
        uses: tj-actions/branch-names@v8
    
      - id: previous
        name: Discover last checked commit
        uses: nrwl/last-successful-commit-action@v1
        with:
          branch: ${{ steps.branches.outputs.current_branch }}
          workflow_id: 'bikeshed.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
      - id: changes
        name: Check for changed files
        uses: tj-actions/changed-files@v42
        with:
          base_sha: ${{ steps.previous.outputs.commit_hash }}
          files: |
            spec/identity/index.bs

  main:

    runs-on: ubuntu-20.04

    permissions:
      contents: write
  
    needs: changes
    
    if: ${{ needs.changes.outputs.changes == 'true' }}

    steps:

      - name: Checkout latest change
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.push.ref }}
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Bikeshed
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade bikeshed
          bikeshed update

      - name: Run Bikeshed
        run: |
          bikeshed spec spec/identity/index.bs

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: process Bikeshed to HTML (CI)'
